### ISSUE TITLE
Can't scroll up past long wrapped text

### ISSUE THREAD

**Issue by Meptl** [psliwka/vim-smoothie#18] opened 2020-07-28 12:10 UTC
Likely the same cause as #16.

Looks to be caused by wrapped lines longer than a single wrap. ~A single wrap works fine.~ I have seen cases of single wraps not working but am finding them to be difficult to reproduce. Example file of just numbers and a long line at line 50: https://gist.github.com/Meptl/2789e4c9ec7ef3c5b54c549d3b2998a0

Versions:
* NVIM v0.3.8
* vim-smoothie (current master) d3de4fbd7a9331b3eb05fa632611ebd34882cc83
* terminal emulator: rxvt-unicode-256color

Steps to reproduce:
1. set wrap
1. Resize your window until the long text line wraps atleast twice
1. Scroll past the wrapped text
1. Attempt to scroll up using <C-b> or <C-u>

I do have an assortment of plugins and have not isolated vim-smoothie.

The fork referenced linked in #16 works, but I'm not a fan of the gg implementation there so would prefer this issue be fixed upstream. I also used the latest of the PR at https://github.com/psliwka/vim-smoothie/pull/13 to no avail.

Love this plugin btw :)

**Comment by psliwka** [comment] 2020-08-14 13:24
Sorry, I couldn't reproduce this neither under neovim 0.4.3 nor vim 8.2. Scrolling over severely wrapped line works fine for me: <https://streamable.com/5fjq76>. Am I missing something?

Also, could you please re-test with up to date nvim?

**Comment by Meptl** [comment] 2020-08-14 15:45
I believe the issue is caused by one of my vim configurations. I have a `set scrolloff=999` which always keeps my cursor in the center of my vim window.

Testing with:
- NVIM v0.4.4
- Minimal .vimrc with just the concat of autoload/smoothie.vim and plugin/smoothie.vim
```
~/vim-smoothie master $ cat autoload/smoothie.vim > smoothie.vim
~/vim-smoothie master $ cat plugin/smoothie.vim >> smoothie.vim
~/vim-smoothie master $ vim -u smoothie.vim ~/gistfile1.txt
```
- Various values for setscroll


I want to say this occurs when scrolloff is greater than half the number of rows in vim this occurs, but the single vs multiwrap situation is still hard for me to reproduce. Playing around with the numbers. (Same steps to reproduce as before; Matching your video)

11 rows (this includes the lines from wrapped text) + scrolloff=6
12 rows (this includes the lines from wrapped text) + scrolloff=7
14 rows (this includes the lines from wrapped text) + scrolloff=8

27 rows + scrolloff=13 Works but the scrollup final line number is off by one. i.e. Press <C-F><C-B> at line 45 will return you to line 44
27 rows + scrolloff=14 Stops at 1 line above the wrapped lines (line 49)

**Comment by MasterMedo** [comment] 2020-11-04 12:14
This has been happening constantly to me recently.
I have isolated vim-smoothie in the `init.vim`:

```vim
call plug#begin('~/.vim/plugged')
    Plug 'psliwka/vim-smoothie'
call plug#end()
set scrolloff=9
```

This bug is extremely hard to reproduce, it depends on the `scrolloff` value, `width` of the terminal, `height` of the terminal, `number of wraps` in a line, positions of wrapped lines in the file and god knows what more.
I can reproduce the bug consistently with the given `init.vim`, terminal width of `85`, terminal height of `22` (gotten with `tput cols` and `tput lines` respectively) and the following file `tmp`:

```
1
2
3
4
5
6
7
8
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaa
9
10
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaa
10
11
12
13
14
15
16
17
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaa
```

With this particular setup **neither scroll down nor scroll up** work correctly with vim-smoothie, but work flawlessly without it. Changing the font size, terminal width, terminal height, scrolloff value or even positions of lines in the file removes the bug completely.

vim version: NVIM v0.5.0-762-g9817d9914
terminal: st 0.8.2
shell: fish, version 3.1.2

I can post a gif if needed.

**Comment by subnut** [comment] 2020-11-16 12:37
I got a GIF -


![gifcast_201116180502](https://user-images.githubusercontent.com/56714626/99253304-8767bd80-2836-11eb-8e75-a1f6d94ca1ff.gif)

**Comment by subnut** [comment] 2020-11-17 05:45
@MasterMedo Thank you for the excellent repro steps :+1:
I have tried to fix this issue in #21 
Please test.

Thank yout

**Comment by MasterMedo** [comment] 2020-11-17 16:19
Yep, switching to 'subnut/vim-smoothie' fixes the issue.

**Comment by subnut** [comment] 2020-11-17 16:48
A gentle warning...

As you may have seen already, I frequently force-push my fork. That happens because I frequently need to go back and make changes to some older commit, so I rebase and force-push the changes.

If you choose to stay on my fork till #21 is merged (I contact Piotr, he said he's gonna merge it in a week), then I suggest you to **not** `git pull` frequently, as it will **always ** result in a merge conflict :sweat_smile: and shall need to be resolved by `git reset --hard origin/master`

**Comment by MasterMedo** [comment] 2020-11-17 16:55
Oh no biggie, I pulled with plug anyway. PlugClean, PlugInstall to the rescue. I'll port back to the original repo when things get merged. Thanks for the heads up, though!

**Closed** 2020-12-25 22:30 UTC
